apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment ## deployment controller name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-template ## what we want to replicate
  template:
    metadata:
      labels:
        app: client-template ## the application name, usually nginx-app
    spec:
      containers:
      - name: demo-client ## just a container name
        image: demo-client ## this is the docker image TAG
        env:
        - name: APP_PORT
          value: "8080"
        - name: APP_ENDPOINT
          value: "go-service"
        imagePullPolicy: Never  ## in order to look at the local docker registry only
        resources:
          limits:
            memory: 256Mi
            cpu: 0.5
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
